spring.application.name=talent-recruitment-api

# ==========================================
# SERVER
# ==========================================

server.port=8080


# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/talent_recruitment_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# JWT
# ==========================================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}


# ==========================================
# SWAGGER / OPENAPI
# ==========================================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


# ==========================================
# GOOGLE OAUTH2
# ==========================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


# ==========================================
# EMAIL
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ==========================================
# ACTUATOR
# ==========================================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=when_authorized

management.info.env.enabled=false