spring.application.name=talent-recruitment-api

server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/talent_recruitment_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:NewPassword123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:myVeryLongSecureJwtSecretKeyForTalentRecruitment2026!}
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

logging.level.org.springframework.security=INFO
logging.level.com.example.talentrecruitment=INFO
