# ==========================================
# DEVELOPMENT PROFILE
# ==========================================

spring.config.activate.on-profile=dev


# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/talent_recruitment_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}


# ==========================================
# JPA
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# JWT
# ==========================================

jwt.expiration=43200000


# ==========================================
# LOGGING
# ==========================================

logging.level.com.example.talentrecruitment=INFO
logging.level.org.springframework.security=INFO


# ==========================================
# ACTUATOR
# ==========================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true