# ==============================
# PRODUCTION CONFIGURATION
# ==============================

server.port=8080

# ==============================
# DATABASE
# ==============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${postgres}
spring.datasource.password=${NewPassword123}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / HIBERNATE
# ==============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# JWT
# ==============================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ==============================
# SWAGGER / OPENAPI
# ==============================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ==============================
# LOGGING
# ==============================

logging.level.com.example.talentrecruitment=INFO
logging.level.org.springframework.security=WARN
logging.file.name=logs/talent-recruitment.log